import * as v from 'valibot';

export const ErrorSchema = v.object({
  success: v.boolean(),
  error: v.string(),
  status: v.number(),
  name: v.string(),
});

export type ErrorDTO = v.InferOutput<typeof ErrorSchema>;

export const Errors = {
  NO_RESOURCE_FOUND: 'Nincs ilyen erőforrás!',
  RESOURCE_ALREADY_EXISTS: 'Ez az erőforrás már létezik!',
  EMAIL_NOT_STRING: 'Az email nem string típusú!',
  EMAIL_NOT_EMAIL: 'Az email nem érvényes!',
  EMAIL_MAX_LENGTH: 'Az email túl hosszú!',
  PASSWORD_NOT_STRING: 'A jelszó nem string típusú!',
  PASSWORD_MIN_LENGTH: 'A jelszó túl rövid!',
  PASSWORD_MAX_LENGTH: 'A jelszó túl hosszú!',
  NAME_NOT_STRING: 'A név nem string típusú!',
  NAME_MIN_LENGTH: 'A név túl rövid!',
  NAME_MAX_LENGTH: 'A név túl hosszú!',
  PRIORITY_NOT_INTEGER: 'A prioritás nem egész szám!',
  PRIORITY_NOT_POSITIVE: 'A prioritás nem lehet negatív!',
  UNSUPPORTED_IMAGE_FORMAT: 'Nem támogatott képformátum!',
  IMAGE_UPLOAD_FAILED: 'A kép feltöltése sikertelen!',
  INVALID_CREDENTIALS: 'Helytelen bejelentkezési adatok!',
  INVALID_CAPTCHA: 'Helytelen captcha!',
  USER_NOT_FOUND: 'Felhasználó nem található!',
  USER_ALREADY_EXISTS: 'A felhasználó már létezik!',
  CAPTCHA_EMPTY: 'A captchát nem töltötted ki!',
  SLUG_NOT_STRING: 'A slug nem string típusú!',
  SLUG_MIN_LENGTH: 'A slug túl rövid!',
  SLUG_MAX_LENGTH: 'A slug túl hosszú!',
  TAG_BG_COLOR_NOT_STRING: 'A címke háttérszíne nem string típusú!',
  TAG_BG_COLOR_INVALID: 'A címke háttérszíne nem egy szín!',
  TAG_TEXT_COLOR_NOT_STRING: 'A címke szövegszíne nem string típusú!',
  TAG_TEXT_COLOR_INVALID: 'A címke szövegszíne nem egy szín!',
  SUBTITLE_NOT_STRING: 'Az alternatív cím nem string típusú!',
  SUBTITLE_MAX_LENGTH: 'Az alternatív cím túl hosszú!',
  PROJECT_TYPE_NOT_VALID: 'A projekt típusa érvénytelen!',
  IMAGE_NOT_VALID: 'A kép érvénytelen!',
  IMAGE_MAX_LENGTH: 'A kép túl hosszú!',
  IMAGE_NOT_URL: 'A kép nem érvényes URL!',
  DESCRIPTION_NOT_VALID: 'A leírás érvénytelen!',
  DESCRIPTION_MAX_LENGTH: 'A leírás túl hosszú!',
  CREATOR_NOT_VALID: 'A készítő érvénytelen!',
  CREATOR_MAX_LENGTH: 'A készítő túl hosszú!',
  TAGS_NOT_ARRAY: 'A címkék nem tömb típusúak!',
  TAGS_NOT_VALID: 'A címkék érvénytelenek!',
  PROJECT_STATUS_NOT_VALID: 'A projekt státusza érvénytelen!',
  TRANSLATED_STATUS_NOT_VALID: 'A projekt lefordított státusza érvénytelen!',
  CHAPTER_COUNT_NOT_VALID: 'A fejezetek száma érvénytelen!',
  CHAPTER_COUNT_MIN_VALUE: 'A fejezetek száma nem lehet negatív!',
  VOLUME_COUNT_NOT_VALID: 'A kötetek száma érvénytelen!',
  VOLUME_COUNT_MIN_VALUE: 'A kötetek száma nem lehet negatív!',
  SUGGESTED_NOT_VALID: 'A kiemelt projekt érték érvénytelen!',
  BANNER_URL_NOT_VALID: 'A banner URL érvénytelen!',
  BANNER_URL_MAX_LENGTH: 'A banner URL túl hosszú!',
  BANNER_URL_NOT_URL: 'A banner URL nem érvényes URL!',
  ID_NOT_STRING: 'Az azonosító nem string típusú!',
  ID_INVALID: 'Ez az azonosító érvénytelen!',
  TITLE_NOT_STRING: 'A cím nem szöveg típusú!',
  TITLE_MIN_LENGTH: 'A cím túl rövid!',
  TITLE_MAX_LENGTH: 'A cím túl hosszú!',
  AUTHOR_NOT_VALID: 'A hír írója érvénytelen!',
  AUTHOR_MAX_LENGTH: 'A hír írójának neve túl hosszú!',
  ROLE_NOT_STRING: 'A szerepkör nem string típusú!',
  ROLE_MAX_LENGTH: 'A szerepkör túl hosszú!',
  DISCORD_NOT_STRING: 'A Discord felhasználónév nem string típusú!',
  DISCORD_MAX_LENGTH: 'A Discord felhasználónév túl hosszú!',
  PROJECT_ID_NOT_VALID: 'A projekt azonosítója érvénytelen!',
  PROJECT_ROLE_NOT_VALID: 'A szerepkör érvénytelen!',
  MEMBER_URL_NOT_STRING: 'A készítő URL nem string típusú!',
  MEMBER_URL_NOT_URL: 'A készítő URL nem érvényes URL!',
  MEMBER_URL_MAX_LENGTH: 'A készítő URL túl hosszú!',
  PROJECT_DOWNLOAD_TYPE_NOT_VALID: 'A letöltés típusa érvénytelen!',
  PROJECT_DOWNLOAD_URL_NOT_URL: 'A letöltés URL nem érvényes URL!',
  PROJECT_DOWNLOAD_URL_MAX_LENGTH: 'A letöltés URL túl hosszú!',
  ANSWER_TOO_LONG: 'A válasz túl hosszú!',
  ANSWER_TOO_SHORT: 'A válasz túl rövid!',
  QUESTION_TOO_LONG: 'A kérdés túl hosszú!',
  QUESTION_TOO_SHORT: 'A kérdés túl rövid!',
  POINTS_TOO_LOW: 'A pontszám nem lehet negatív!',
  QUESTION_SET_TITLE_TOO_LONG: 'A kérdéssor címe túl hosszú!',
  QUESTION_SET_TITLE_TOO_SHORT: 'A kérdéssor címe túl rövid!',
  QUESTION_SET_DESCRIPTION_TOO_LONG: 'A kérdéssor leírása túl hosszú!',
  MIN_POINTS_TOO_LOW: 'A minimális pontszám nem lehet negatív!',
  QUESTIONS_TO_CHOOSE_TOO_LOW:
    'A választható kérdések száma nem lehet negatív!',
  QUESTION_SET_NO_QUESTIONS: 'A kérdéssor nem tartalmaz kérdéseket!',
  QUESTION_NO_OPTIONS: 'A kérdés nem tartalmaz elég válaszlehetőséget!',
  QUESTION_NO_CORRECT_OPTIONS:
    'A kérdés nem tartalmaz helyes válaszlehetőséget!',
  QUIZ_NO_QUESTION_SETS: 'A kvíz nem tartalmaz kérdéssorokat!',
  QUIZ_TITLE_TOO_LONG: 'A kvíz címe túl hosszú!',
  QUIZ_TITLE_TOO_SHORT: 'A kvíz címe túl rövid!',
  QUIZ_DESCRIPTION_TOO_LONG: 'A kvíz leírása túl hosszú!',
  IMAGE_URL_TOO_LONG: 'A kép URL-je túl hosszú!',
  IMAGE_URL_INVALID: 'A kép URL-je érvénytelen!',
};
